import { useMemo, useState } from "react";
import { Link } from "react-router-dom";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";

const icons = {
  mission: "◎", vision: "◇", people: "✦", match: "⌘", progress: "↗",
  code: "</>", heart: "♡", spark: "✦", search: "⌕", mail: "✉",
  pin: "⌖", clock: "◷", phone: "◌", resume: "▤", interview: "◈",
  guide: "↗", book: "▱", shield: "◒", scale: "§"
};

const Icon = ({ name, dark = false }) => <span className={`public-icon ${dark ? "public-icon-dark" : ""}`} aria-hidden="true">{icons[name]}</span>;

const Page = ({ eyebrow, title, intro, children, aside }) => (
  <>
    <Navbar />
    <main className="overflow-hidden bg-white text-slate-900">
      <section className="px-4 pt-7 sm:px-6 lg:px-8">
        <div className="relative mx-auto max-w-7xl overflow-hidden rounded-[2rem] bg-slate-950 px-6 py-14 text-center text-white shadow-2xl shadow-slate-950/15 sm:px-12 sm:py-20">
          <div className="public-orb public-orb-one" /><div className="public-orb public-orb-two" />
          <div className="relative mx-auto max-w-3xl">
            <p className="text-xs font-bold uppercase tracking-[0.2em] text-blue-300">{eyebrow}</p>
            <h1 className="mt-5 text-4xl font-bold tracking-tight sm:text-5xl lg:text-6xl">{title}</h1>
            <p className="mt-5 text-base leading-7 text-slate-300 sm:text-lg">{intro}</p>
          </div>
        </div>
      </section>
      <div className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8 lg:py-24">{aside ? <div className="lg:grid lg:grid-cols-[220px_minmax(0,1fr)] lg:gap-16">{aside}<div>{children}</div></div> : children}</div>
    </main>
    <Footer />
  </>
);

const Section = ({ eyebrow, title, intro, children, className = "" }) => <section className={`public-section ${className}`}>
  {eyebrow && <p className="text-xs font-bold uppercase tracking-[0.18em] text-blue-600">{eyebrow}</p>}
  {title && <h2 className="mt-3 text-3xl font-bold tracking-tight text-slate-950 sm:text-4xl">{title}</h2>}
  {intro && <p className="mt-4 max-w-2xl text-base leading-7 text-slate-600">{intro}</p>}
  {children && <div className="mt-9">{children}</div>}
</section>;

const Card = ({ icon, title, children, className = "" }) => <article className={`public-card ${className}`}>
  {icon && <Icon name={icon} />}
  <h3 className={`${icon ? "mt-5" : ""} text-xl font-bold tracking-tight text-slate-950`}>{title}</h3>
  <div className="mt-3 text-sm leading-6 text-slate-600">{children}</div>
</article>;

const Button = ({ to, children, variant = "primary" }) => <Link to={to} className={`public-button public-button-${variant}`}>{children}<span aria-hidden="true">→</span></Link>;

export const About = () => <Page eyebrow="About Job Portal" title="Better hiring for the people who build technology." intro="We make it easier for software professionals to find teams where their skills, ambition, and work can make a real difference.">
  <Section eyebrow="Our purpose" title="A clearer path to meaningful work." intro="Job Portal gives technical talent and growing teams a more considered way to meet.">
    <div className="grid gap-5 md:grid-cols-2"><Card icon="mission" title="Our mission">Make technical hiring clearer, fairer, and more useful for every candidate and hiring team.</Card><Card icon="vision" title="Our vision">Create a hiring experience where developers spend less time guessing and more time finding the right fit.</Card></div>
  </Section>
  <Section eyebrow="Why Job Portal" title="Designed around how developers actually choose roles.">
    <div className="grid gap-5 md:grid-cols-3"><Card icon="match" title="Relevant from the start">Find roles with the details that matter: stack, level, location, and team expectations.</Card><Card icon="progress" title="Built for momentum">Keep your profile ready, track applications, and focus your energy on the next good conversation.</Card><Card icon="people" title="A more human process">We believe thoughtful information and respectful connections lead to better decisions for everyone.</Card></div>
  </Section>
  <Section eyebrow="The platform" title="Everything you need to move with confidence.">
    <div className="rounded-[2rem] bg-blue-50 p-7 sm:p-10"><div className="grid gap-8 md:grid-cols-3"><div><p className="text-3xl font-bold text-blue-600">Focused</p><p className="mt-2 text-sm leading-6 text-slate-600">Technology opportunities, not a noisy general job board.</p></div><div><p className="text-3xl font-bold text-blue-600">Practical</p><p className="mt-2 text-sm leading-6 text-slate-600">Resume-ready applications and skill-aware discovery.</p></div><div><p className="text-3xl font-bold text-blue-600">Transparent</p><p className="mt-2 text-sm leading-6 text-slate-600">Clearer role information so you can decide where to invest your time.</p></div></div></div>
  </Section>
  <Section eyebrow="Developer-first" title="Great careers are built on craft, not keyword games." intro="We design for the people doing the work: the engineers who care about useful problems, clear trade-offs, and teams that help them grow. That means putting practical skills and honest opportunities at the center of the experience." />
</Page>;

const workValues = [["code", "Useful work", "We build practical tools that make a complicated process feel simpler."], ["heart", "People before process", "Kind feedback, inclusive decisions, and respect for candidates guide how we work."], ["spark", "Room to own", "Bring your judgment, improve the details, and see your ideas become part of the product."]];
export const Careers = () => <Page eyebrow="Careers at Job Portal" title="Help us make technical hiring better." intro="Join a thoughtful team building a more useful, more human way for developers and hiring teams to connect.">
  <Section eyebrow="Life here" title="Small team. High trust. Meaningful impact."><div className="grid gap-5 md:grid-cols-3">{workValues.map(([icon, title, body]) => <Card key={title} icon={icon} title={title}>{body}</Card>)}</div></Section>
  <Section eyebrow="How we hire" title="A transparent process, from hello to offer."><div className="grid gap-5 md:grid-cols-4">{[["01", "Introduce yourself", "A short conversation about your experience and what you want next."], ["02", "Meet the team", "Explore the role, the work, and how we collaborate."], ["03", "Work together", "A practical, respectful exercise built around the role."], ["04", "Decide clearly", "We share timely feedback and make a thoughtful decision."]].map(([number, title, body]) => <div key={number} className="border-t-2 border-blue-600 pt-5"><p className="text-xs font-bold tracking-[0.16em] text-blue-600">{number}</p><h3 className="mt-3 font-bold text-slate-950">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{body}</p></div>)}</div></Section>
  <Section eyebrow="Open roles" title="Find your place here." intro="We do not have any published openings at this time."><div className="rounded-[2rem] border border-dashed border-slate-300 bg-slate-50 px-6 py-12 text-center"><span className="mx-auto flex h-12 w-12 items-center justify-center rounded-2xl bg-white text-xl text-blue-600 shadow-sm">✦</span><h3 className="mt-5 text-xl font-bold text-slate-950">No openings right now</h3><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-slate-600">We are growing thoughtfully. Please check back soon for opportunities to build with us.</p><div className="mt-6"><Button to="/contact" variant="secondary">Get in touch</Button></div></div></Section>
</Page>;

export const Contact = () => { const [sent, setSent] = useState(false); return <Page eyebrow="Contact" title="Let's start a conversation." intro="Whether you need product help, have feedback, or want to learn more about Job Portal, our team is here.">
  <div className="grid gap-10 lg:grid-cols-[1.05fr_.95fr]"><section className="public-card"><p className="text-xs font-bold uppercase tracking-[0.18em] text-blue-600">Send a message</p><h2 className="mt-3 text-3xl font-bold tracking-tight text-slate-950">How can we help?</h2><form className="mt-8 grid gap-4" onSubmit={(event) => { event.preventDefault(); setSent(true); }}><label className="public-label">Your name<input required className="public-input" placeholder="Jane Smith" /></label><label className="public-label">Email address<input required type="email" className="public-input" placeholder="jane@example.com" /></label><label className="public-label">Your message<textarea required rows="5" className="public-input resize-y" placeholder="Tell us a little about how we can help." /></label><button className="public-submit" type="submit">Send message <span aria-hidden="true">→</span></button>{sent && <p className="rounded-xl bg-emerald-50 px-4 py-3 text-sm font-medium text-emerald-800">Thanks for reaching out. Your message has been noted.</p>}</form></section><div className="grid content-start gap-5 sm:grid-cols-2 lg:grid-cols-1"><Card icon="mail" title="Email us">support@jobportal.example</Card><Card icon="clock" title="Business hours">Monday to Friday<br />9:00 AM to 6:00 PM IST</Card><Card icon="pin" title="Our office" className="sm:col-span-2 lg:col-span-1">Bengaluru, India<br /><span className="text-slate-400">Office location placeholder</span></Card></div></div>
  <Section eyebrow="Visit us" title="A place for good conversations."><div className="relative flex min-h-64 items-end overflow-hidden rounded-[2rem] bg-slate-100 p-7"><div className="absolute inset-0 public-map-pattern" /><div className="relative rounded-2xl bg-white p-5 shadow-lg"><Icon name="pin" /><p className="mt-3 font-bold text-slate-950">Bengaluru, India</p><p className="mt-1 text-sm text-slate-600">Our office location will appear here.</p></div></div></Section>
</Page>; };

const resources = [["resume", "Resume tips", "Make your impact easy to see", "Show outcomes, technologies, and the projects most relevant to the role you want."], ["interview", "Interview preparation", "Walk in ready to collaborate", "Practice explaining your decisions, reviewing fundamentals, and asking thoughtful questions."], ["guide", "Career guides", "Build a job search you can sustain", "Set a focused rhythm, research teams, and keep your next steps clear."], ["book", "Engineering resources", "Keep learning with intention", "Choose practical skills and projects that move you closer to the work you want to do."]];
export const Resources = () => <Page eyebrow="Developer resources" title="Practical guidance for your next role." intro="A focused collection of career advice for software professionals navigating their next move."><div className="grid gap-5 md:grid-cols-2">{resources.map(([icon, title, subtitle, body]) => <article key={title} className="public-card group flex min-h-72 flex-col"><Icon name={icon} /><p className="mt-6 text-xs font-bold uppercase tracking-[0.16em] text-blue-600">{subtitle}</p><h2 className="mt-3 text-2xl font-bold tracking-tight text-slate-950">{title}</h2><p className="mt-3 text-sm leading-6 text-slate-600">{body}</p><span className="mt-auto pt-6 text-sm font-bold text-blue-600">Explore guidance <span className="ml-1 transition-transform group-hover:translate-x-1">→</span></span></article>)}</div><Section eyebrow="A better next step" title="Small, useful moves add up." intro="Use these resources alongside a current profile and a clear picture of the work you want to do next."><Button to="/" >Browse open roles</Button></Section></Page>;

const faqItems = [["How do I apply for a job?", "Open a role, select Apply, and sign in. Keep your resume current so your application is ready to submit."], ["How does resume matching work?", "When you upload a PDF resume, the platform identifies listed skills and uses them to surface relevant roles first."], ["Can freshers apply?", "Yes. Review each role's experience level and apply to opportunities that fit your current skills and interests."], ["How do recruiters contact candidates?", "Recruiters review submitted applications and contact candidates using the details available with their application."], ["How do I update my resume?", "Open Profile and upload a new PDF resume. The latest upload replaces the previous file and refreshes your matching data."], ["How do I delete my account?", "Use your account settings to manage your account, or contact support for help with an account deletion request."]];
export const Help = () => { const [open, setOpen] = useState(0); const [query, setQuery] = useState(""); const shown = useMemo(() => faqItems.filter(([q, a]) => `${q} ${a}`.toLowerCase().includes(query.toLowerCase())), [query]); return <Page eyebrow="Help center" title="Answers, when you need them." intro="Quick guidance for using Job Portal, applying with confidence, and keeping your profile up to date."><div className="mx-auto max-w-4xl"><label className="relative block"><span className="pointer-events-none absolute left-5 top-4 text-lg text-slate-400">⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} className="w-full rounded-2xl border border-slate-200 bg-white py-4 pl-12 pr-5 text-sm shadow-sm outline-none transition focus:border-blue-500 focus:ring-4 focus:ring-blue-100" placeholder="Search for an answer" /></label><div className="mt-8 overflow-hidden rounded-[1.5rem] border border-slate-200 bg-white shadow-sm">{shown.length ? shown.map(([question, answer]) => { const isOpen = open === question; return <div className="border-b border-slate-100 last:border-0" key={question}><button onClick={() => setOpen(isOpen ? "" : question)} className="flex w-full items-center justify-between gap-5 px-6 py-5 text-left text-base font-bold text-slate-950 sm:px-7"><span>{question}</span><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-blue-50 text-lg font-normal text-blue-600">{isOpen ? "−" : "+"}</span></button>{isOpen && <p className="max-w-3xl px-6 pb-6 text-sm leading-7 text-slate-600 sm:px-7">{answer}</p>}</div>; }) : <div className="px-6 py-12 text-center"><p className="font-bold text-slate-950">No answers found</p><p className="mt-2 text-sm text-slate-600">Try a different search or contact our support team.</p></div>}</div><p className="mt-8 text-center text-sm text-slate-600">Still need help? <Link to="/contact" className="font-bold text-blue-600 hover:text-blue-700">Contact our team</Link>.</p></div></Page>; };

const policySections = [["Information we collect", "We collect account details you provide, including your name, email address, profile information, resume data, and activity necessary to provide the platform."], ["How we use information", "We use information to operate the platform, process applications, improve matching and support features, maintain security, and communicate important service updates."], ["Sharing information", "We share application information with the relevant recruiting organization when you apply. We do not sell personal information."], ["Security and retention", "We use reasonable safeguards and retain information only as long as needed for the platform, legal obligations, and legitimate business purposes."], ["Your choices", "You may update profile information through your account. Contact us for privacy questions or deletion requests."]];
const termsSections = [["Using the platform", "Use Job Portal lawfully and provide accurate, current information. You are responsible for maintaining the security of your account."], ["Applications and recruiters", "Submitting an application does not guarantee an interview or offer. Recruiters independently manage their roles and hiring decisions."], ["Content and conduct", "Do not upload unlawful, misleading, harmful, or infringing content, or interfere with the platform's security or operation."], ["Availability", "We work to keep the platform available and useful, but features may change, be interrupted, or be unavailable from time to time."], ["Changes and contact", "We may update these terms when necessary. Continued use after an update means you accept the revised terms. Contact support with questions."]];

const Legal = ({ privacy }) => { const sections = privacy ? policySections : termsSections; const title = privacy ? "Privacy Policy" : "Terms & Conditions"; return <Page eyebrow="Legal" title={title} intro={privacy ? "This policy explains how Job Portal handles personal information when you use our platform." : "These terms describe the rules for using Job Portal and submitting applications through it."} aside={<aside className="mb-10 hidden lg:block"><div className="sticky top-28 border-l border-slate-200 pl-5"><p className="text-xs font-bold uppercase tracking-[0.16em] text-slate-400">On this page</p><nav className="mt-4 flex flex-col gap-3">{sections.map(([heading]) => <a key={heading} className="text-sm text-slate-600 hover:text-blue-600" href={`#${heading.toLowerCase().replaceAll(" ", "-")}`}>{heading}</a>)}<a className="text-sm text-slate-600 hover:text-blue-600" href="#contact">Contact</a></nav></div></aside>}><article className="max-w-3xl"><p className="mb-12 rounded-xl bg-slate-50 px-4 py-3 text-sm text-slate-500">Last updated: July 19, 2026</p>{sections.map(([heading, body]) => <section key={heading} id={heading.toLowerCase().replaceAll(" ", "-")} className="scroll-mt-32 border-b border-slate-100 py-9 first:pt-0"><h2 className="text-2xl font-bold tracking-tight text-slate-950">{heading}</h2><p className="mt-4 text-base leading-8 text-slate-600">{body}</p></section>)}<section id="contact" className="scroll-mt-32 py-9"><h2 className="text-2xl font-bold tracking-tight text-slate-950">Contact</h2><p className="mt-4 text-base leading-8 text-slate-600">For questions about {privacy ? "this policy" : "these terms"}, please contact us at support@jobportal.example.</p></section></article></Page>; };
export const Privacy = () => <Legal privacy />;
export const Terms = () => <Legal />;
